spring:
  application:
    name: MSBanque
  data:
    mongodb:
      host: localhost
      port: 27017
      database: banque_db_test
      # authentication-database: admin
      # username: banque_user
      # password: banque_password

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG

app:
  banque:
    nom: MaBanque
    devise: EUR

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
