#spring:
#  application:
#    name: ms-banque
##    ajouter l'url de config server
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: banque_db_test
#  cloud:
#    inetutils:
#      prefer-hostname-over-ip: true
#
#server:
#  port: 8082
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ms-banque
  #  profiles:
  #    active: DEV
  config:
    import: optional:configserver:http://localhost:8888
# Facultatif mais recommandé
logging:
  level:
    root: INFO

# Définir l'URL de Eureka de manière dynamique:
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
