#spring:
#  application:
#    name: ms-banque
##    ajouter l'url de config server
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: banque_db_test
#  cloud:
#    inetutils:
#      prefer-hostname-over-ip: true
#
#server:
#  port: 8082
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ms-banque
  #  profiles:
  #  active: DEV
  config:
    import: optional:configserver:http://localhost:8888

  # configuration Kafka:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ms-banque-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"  # indispensable pour désérialiser CompteDto

#    producer: # désactiver pour résoudre Problème de sérialisation côté producteur
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Facultatif mais recommandé
logging:
  level:
    root: INFO

# Définir l'URL de Eureka de manière dynamique:
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}



